// Generated by Tmds.DBus.Tool v0.93.0 with arguments: codegen --service org.mpris.MediaPlayer2.playerctld --tmds-dbus-api
using System.Runtime.CompilerServices;
using Tmds.DBus;
[assembly: InternalsVisibleTo(Tmds.DBus.Connection.DynamicAssemblyName)]

#pragma warning disable CS8625 // Cannot convert null literal to non-nullable reference type.

namespace HoscyCore.Services.Media.Backends;

[DBusInterface("org.mpris.MediaPlayer2")]
public interface IMprisMediaPlayer2 : IDBusObject
{
    Task RaiseAsync();
    Task QuitAsync();
    Task<T> GetAsync<T>(string prop);
    Task<MprisMediaPlayer2Properties> GetAllAsync();
    Task SetAsync(string prop, object val);
    Task<IDisposable> WatchPropertiesAsync(Action<PropertyChanges> handler);
}

[Dictionary]
public class MprisMediaPlayer2Properties
{
    private bool _CanQuit = default;
    public bool CanQuit
    {
        get { return _CanQuit; }
        set { _CanQuit = value; }
    }
    private bool _Fullscreen = default;
    public bool Fullscreen
    {
        get { return _Fullscreen; }
        set { _Fullscreen = value; }
    }
    private bool _CanSetFullscreen = default;
    public bool CanSetFullscreen
    {
        get { return _CanSetFullscreen; }
        set { _CanSetFullscreen = value; }
    }
    private bool _CanRaise = default;
    public bool CanRaise
    {
        get { return _CanRaise; }
        set { _CanRaise = value; }
    }
    private bool _HasTrackList = default;
    public bool HasTrackList
    {
        get { return _HasTrackList; }
        set { _HasTrackList = value; }
    }
    private string _Identity = default;
    public string Identity
    {
        get { return _Identity; }
        set { _Identity = value; }
    }
    private string _DesktopEntry = default;
    public string DesktopEntry
    {
        get { return _DesktopEntry; }
        set { _DesktopEntry = value; }
    }
    private string[] _SupportedUriSchemes = default;
    public string[] SupportedUriSchemes
    {
        get { return _SupportedUriSchemes; }
        set { _SupportedUriSchemes = value; }
    }
    private string[] _SupportedMimeTypes = default;
    public string[] SupportedMimeTypes
    {
        get { return _SupportedMimeTypes; }
        set { _SupportedMimeTypes = value; }
    }
}

public static class MprisMediaPlayer2Extensions
{
    public static Task<bool> GetCanQuitAsync(this IMprisMediaPlayer2 o) => o.GetAsync<bool>("CanQuit");
    public static Task<bool> GetFullscreenAsync(this IMprisMediaPlayer2 o) => o.GetAsync<bool>("Fullscreen");
    public static Task<bool> GetCanSetFullscreenAsync(this IMprisMediaPlayer2 o) => o.GetAsync<bool>("CanSetFullscreen");
    public static Task<bool> GetCanRaiseAsync(this IMprisMediaPlayer2 o) => o.GetAsync<bool>("CanRaise");
    public static Task<bool> GetHasTrackListAsync(this IMprisMediaPlayer2 o) => o.GetAsync<bool>("HasTrackList");
    public static Task<string> GetIdentityAsync(this IMprisMediaPlayer2 o) => o.GetAsync<string>("Identity");
    public static Task<string> GetDesktopEntryAsync(this IMprisMediaPlayer2 o) => o.GetAsync<string>("DesktopEntry");
    public static Task<string[]> GetSupportedUriSchemesAsync(this IMprisMediaPlayer2 o) => o.GetAsync<string[]>("SupportedUriSchemes");
    public static Task<string[]> GetSupportedMimeTypesAsync(this IMprisMediaPlayer2 o) => o.GetAsync<string[]>("SupportedMimeTypes");
    public static Task SetFullscreenAsync(this IMprisMediaPlayer2 o, bool val) => o.SetAsync("Fullscreen", val);
}

[DBusInterface("com.github.altdesktop.playerctld")]
public interface IMprisPlayerctld : IDBusObject
{
    Task<string> ShiftAsync();
    Task<string> UnshiftAsync();
    Task<IDisposable> WatchActivePlayerChangeBeginAsync(Action<string> handler, Action<Exception> onError = null);
    Task<IDisposable> WatchActivePlayerChangeEndAsync(Action<string> handler, Action<Exception> onError = null);
    Task<T> GetAsync<T>(string prop);
    Task<MprisPlayerctldProperties> GetAllAsync();
    Task SetAsync(string prop, object val);
    Task<IDisposable> WatchPropertiesAsync(Action<PropertyChanges> handler);
}

[Dictionary]
public class MprisPlayerctldProperties
{
    private string[] _PlayerNames = default;
    public string[] PlayerNames
    {
        get { return _PlayerNames; }
        set { _PlayerNames = value; }
    }
}

public static class MprisPlayerctldExtensions
{
    public static Task<string[]> GetPlayerNamesAsync(this IMprisPlayerctld o) => o.GetAsync<string[]>("PlayerNames");
}

[DBusInterface("org.mpris.MediaPlayer2.Playlists")]
public interface IMprisPlaylists : IDBusObject
{
    Task ActivatePlaylistAsync(ObjectPath PlaylistId);
    Task<(ObjectPath, string, string)[]> GetPlaylistsAsync(uint Index, uint MaxCount, string Order, bool ReverseOrder);
    Task<IDisposable> WatchPlaylistChangedAsync(Action<(ObjectPath, string, string)> handler, Action<Exception> onError = null);
    Task<T> GetAsync<T>(string prop);
    Task<MprisPlaylistsProperties> GetAllAsync();
    Task SetAsync(string prop, object val);
    Task<IDisposable> WatchPropertiesAsync(Action<PropertyChanges> handler);
}

[Dictionary]
public class MprisPlaylistsProperties
{
    private uint _PlaylistCount = default;
    public uint PlaylistCount
    {
        get { return _PlaylistCount; }
        set { _PlaylistCount = value; }
    }
    private string[] _Orderings = default;
    public string[] Orderings
    {
        get { return _Orderings; }
        set { _Orderings = value; }
    }
    private (bool, (ObjectPath, string, string)) _ActivePlaylist = default;
    public (bool, (ObjectPath, string, string)) ActivePlaylist
    {
        get { return _ActivePlaylist; }
        set { _ActivePlaylist = value; }
    }
}

public static class MprisPlaylistsExtensions
{
    public static Task<uint> GetPlaylistCountAsync(this IMprisPlaylists o) => o.GetAsync<uint>("PlaylistCount");
    public static Task<string[]> GetOrderingsAsync(this IMprisPlaylists o) => o.GetAsync<string[]>("Orderings");
    public static Task<(bool, (ObjectPath, string, string))> GetActivePlaylistAsync(this IMprisPlaylists o) => o.GetAsync<(bool, (ObjectPath, string, string))>("ActivePlaylist");
}

[DBusInterface("org.mpris.MediaPlayer2.Player")]
public interface IMprisPlayer : IDBusObject
{
    Task NextAsync();
    Task PreviousAsync();
    Task PauseAsync();
    Task PlayPauseAsync();
    Task StopAsync();
    Task PlayAsync();
    Task SeekAsync(long Offset);
    Task SetPositionAsync(ObjectPath TrackId, long Offset);
    Task OpenUriAsync(string Uri);
    Task<IDisposable> WatchSeekedAsync(Action<long> handler, Action<Exception> onError = null);
    Task<T> GetAsync<T>(string prop);
    Task<MprisPlayerProperties> GetAllAsync();
    Task SetAsync(string prop, object val);
    Task<IDisposable> WatchPropertiesAsync(Action<PropertyChanges> handler);
}

[Dictionary]
public class MprisPlayerProperties
{
    private string _PlaybackStatus = default;
    public string PlaybackStatus
    {
        get { return _PlaybackStatus; }
        set { _PlaybackStatus = value; }
    }
    private string _LoopStatus = default;
    public string LoopStatus
    {
        get { return _LoopStatus; }
        set { _LoopStatus = value; }
    }
    private double _Rate = default;
    public double Rate
    {
        get { return _Rate; }
        set { _Rate = value; }
    }
    private bool _Shuffle = default;
    public bool Shuffle
    {
        get { return _Shuffle; }
        set { _Shuffle = value; }
    }
    private IDictionary<string, object> _Metadata = default;
    public IDictionary<string, object> Metadata
    {
        get { return _Metadata; }
        set { _Metadata = value; }
    }
    private double _Volume = default;
    public double Volume
    {
        get { return _Volume; }
        set { _Volume = value; }
    }
    private long _Position = default;
    public long Position
    {
        get { return _Position; }
        set { _Position = value; }
    }
    private double _MinimumRate = default;
    public double MinimumRate
    {
        get { return _MinimumRate; }
        set { _MinimumRate = value; }
    }
    private double _MaximumRate = default;
    public double MaximumRate
    {
        get { return _MaximumRate; }
        set { _MaximumRate = value; }
    }
    private bool _CanGoNext = default;
    public bool CanGoNext
    {
        get { return _CanGoNext; }
        set { _CanGoNext = value; }
    }
    private bool _CanGoPrevious = default;
    public bool CanGoPrevious
    {
        get { return _CanGoPrevious; }
        set { _CanGoPrevious = value; }
    }
    private bool _CanPlay = default;
    public bool CanPlay
    {
        get { return _CanPlay; }
        set { _CanPlay = value; }
    }
    private bool _CanPause = default;
    public bool CanPause
    {
        get { return _CanPause; }
        set { _CanPause = value; }
    }
    private bool _CanSeek = default;
    public bool CanSeek
    {
        get { return _CanSeek; }
        set { _CanSeek = value; }
    }
    private bool _CanControl = default;
    public bool CanControl
    {
        get { return _CanControl; }
        set { _CanControl = value; }
    }
}

public static class MprisPlayerExtensions
{
    public static Task<string> GetPlaybackStatusAsync(this IMprisPlayer o) => o.GetAsync<string>("PlaybackStatus");
    public static Task<string> GetLoopStatusAsync(this IMprisPlayer o) => o.GetAsync<string>("LoopStatus");
    public static Task<double> GetRateAsync(this IMprisPlayer o) => o.GetAsync<double>("Rate");
    public static Task<bool> GetShuffleAsync(this IMprisPlayer o) => o.GetAsync<bool>("Shuffle");
    public static Task<IDictionary<string, object>> GetMetadataAsync(this IMprisPlayer o) => o.GetAsync<IDictionary<string, object>>("Metadata");
    public static Task<double> GetVolumeAsync(this IMprisPlayer o) => o.GetAsync<double>("Volume");
    public static Task<long> GetPositionAsync(this IMprisPlayer o) => o.GetAsync<long>("Position");
    public static Task<double> GetMinimumRateAsync(this IMprisPlayer o) => o.GetAsync<double>("MinimumRate");
    public static Task<double> GetMaximumRateAsync(this IMprisPlayer o) => o.GetAsync<double>("MaximumRate");
    public static Task<bool> GetCanGoNextAsync(this IMprisPlayer o) => o.GetAsync<bool>("CanGoNext");
    public static Task<bool> GetCanGoPreviousAsync(this IMprisPlayer o) => o.GetAsync<bool>("CanGoPrevious");
    public static Task<bool> GetCanPlayAsync(this IMprisPlayer o) => o.GetAsync<bool>("CanPlay");
    public static Task<bool> GetCanPauseAsync(this IMprisPlayer o) => o.GetAsync<bool>("CanPause");
    public static Task<bool> GetCanSeekAsync(this IMprisPlayer o) => o.GetAsync<bool>("CanSeek");
    public static Task<bool> GetCanControlAsync(this IMprisPlayer o) => o.GetAsync<bool>("CanControl");
    public static Task SetLoopStatusAsync(this IMprisPlayer o, string val) => o.SetAsync("LoopStatus", val);
    public static Task SetRateAsync(this IMprisPlayer o, double val) => o.SetAsync("Rate", val);
    public static Task SetShuffleAsync(this IMprisPlayer o, bool val) => o.SetAsync("Shuffle", val);
    public static Task SetVolumeAsync(this IMprisPlayer o, double val) => o.SetAsync("Volume", val);
}

[DBusInterface("org.mpris.MediaPlayer2.TrackList")]
public interface IMprisTrackList : IDBusObject
{
    Task<IDictionary<string, object>[]> GetTracksMetadataAsync(ObjectPath[] TrackIds);
    Task AddTrackAsync(string Uri, ObjectPath AfterTrack, bool SetAsCurrent);
    Task RemoveTrackAsync(ObjectPath TrackId);
    Task GoToAsync(ObjectPath TrackId);
    Task<IDisposable> WatchTrackListReplacedAsync(Action<(ObjectPath[] tracks, ObjectPath currentTrack)> handler, Action<Exception> onError = null);
    Task<IDisposable> WatchTrackAddedAsync(Action<(IDictionary<string, object> metadata, ObjectPath afterTrack)> handler, Action<Exception> onError = null);
    Task<IDisposable> WatchTrackRemovedAsync(Action<ObjectPath> handler, Action<Exception> onError = null);
    Task<IDisposable> WatchTrackMetadataChangedAsync(Action<(ObjectPath trackId, IDictionary<string, object> metadata)> handler, Action<Exception> onError = null);
    Task<T> GetAsync<T>(string prop);
    Task<MprisTrackListProperties> GetAllAsync();
    Task SetAsync(string prop, object val);
    Task<IDisposable> WatchPropertiesAsync(Action<PropertyChanges> handler);
}

[Dictionary]
public class MprisTrackListProperties
{
    private ObjectPath[] _Tracks = default;
    public ObjectPath[] Tracks
    {
        get { return _Tracks; }
        set { _Tracks = value; }
    }
    private bool _CanEditTracks = default;
    public bool CanEditTracks
    {
        get { return _CanEditTracks; }
        set { _CanEditTracks = value; }
    }
}

public static class MprisTrackListExtensions
{
    public static Task<ObjectPath[]> GetTracksAsync(this IMprisTrackList o) => o.GetAsync<ObjectPath[]>("Tracks");
    public static Task<bool> GetCanEditTracksAsync(this IMprisTrackList o) => o.GetAsync<bool>("CanEditTracks");
}
